import express from "express";
import ChartController from "../controllers/Chart.controller";
import ENDPOINTS from "../utils/Endpoints";
const routes = express.Router();
const chartController = new ChartController();
routes.get(ENDPOINTS.SANKEY, chartController.getSankeyChart);
routes.get(ENDPOINTS.DONUT, chartController.getDonutChart);
routes.get(ENDPOINTS.WORD_CLOUD, chartController.getWordCloud);
routes.get(ENDPOINTS.STACKED, chartController.getStackedGraph);
routes.get(ENDPOINTS.LINE, chartController.getLineChart);
routes.get(ENDPOINTS.SCATTER_PLOT, chartController.getScatterPlot);
export default  routes;
